INSERT INTO Artist (name, country) VALUES
('Pink Floyd', 'United Kingdom'),
('Queen', 'United Kingdom'),
('Led Zeppelin', 'United Kingdom'),
('AC/DC', 'Australia'),
('Aerosmith', 'United States'),
('Ozzy Osbourne', 'United Kingdom'),
('The Cranberries', 'Ireland'),
('Black Sabbath', 'United Kingdom'),
('Nirvana', 'United States'),
('Adele', 'United Kingdom'),
('The Beach Boys', 'United States'),
('Harry Nilsson', 'United States'),
('The Corgies', 'United Kingdom'),
('ELO', 'United Kingdom'),
('David Bowie', 'United Kingdom'),
('Beck', 'United States'),
('David Rawlings', 'United States'),
('Nick Cave and the Bad Seeds', 'Australia'),
('Adam Levine', 'United States'),
('Blue Swede', 'Sweden'),
('Huey Lewis and the News', 'United States');