INSERT INTO Song (title, duration, artist_id) VALUES
-- A Night at the Opera (1975)
('Death on Two Legs', '00:03:43', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Lazing on a Sunday Afternoon', '00:01:08', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('I''m in Love with My Car', '00:03:05', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('You''re My Best Friend', '00:02:50', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('''39', '00:03:25', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Sweet Lady', '00:04:01', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Seaside Rendezvous', '00:02:13', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('The Prophet''s Song', '00:08:17', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Love of My Life', '00:03:38', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Good Company', '00:03:26', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Bohemian Rhapsody', '00:05:55', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('God Save the Queen', '00:01:11', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- A Kind of Magic (1986)
('One Vision', '00:05:10', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('A Kind of Magic', '00:04:24', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('One Year of Love', '00:04:26', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Pain Is So Close to Pleasure', '00:04:21', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Friends Will Be Friends', '00:04:07', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Who Wants to Live Forever', '00:05:15', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Gimme the Prize', '00:04:34', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Don''t Lose Your Head', '00:04:38', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Princes of the Universe', '00:03:32', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- News of the World (1977)
('We Will Rock You', '00:02:02', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('We Are the Champions', '00:03:00', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Sheer Heart Attack', '00:03:26', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('All Dead, All Dead', '00:03:10', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Spread Your Wings', '00:04:34', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Fight from the Inside', '00:03:03', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Get Down, Make Love', '00:03:51', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Sleeping on the Sidewalk', '00:03:06', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Who Needs You', '00:03:05', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('It''s Late', '00:06:26', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('My Melancholy Blues', '00:03:29', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- The Game (1980)
('Play the Game', '00:03:30', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Dragon Attack', '00:04:18', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Another One Bites the Dust', '00:03:36', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Need Your Loving Tonight', '00:02:48', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Crazy Little Thing Called Love', '00:02:43', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Rock It (Prime Jive)', '00:04:31', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Don''t Try Suicide', '00:03:52', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Sail Away Sweet Sister', '00:3:32', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Coming Soon', '00:2:51', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Save Me', '00:3:48', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- The Works (1984)
('Radio Ga Ga', '00:05:48', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Tear It Up', '00:03:28', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('It''s a Hard Life', '00:04:08', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Man on the Prowl', '00:03:28', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Machines (Or ''Back to Humans'')', '00:05:10', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('I Want to Break Free', '00:03:20', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Keep Passing the Open Windows', '00:05:21', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Hammer to Fall', '00:04:28', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Is This the World We Created...?', '00:02:13', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- Innuendo (1991)
('Innuendo', '00:06:31', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('I''m Going Slightly Mad', '00:04:22', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Headlong', '00:04:38', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('I Can''t Live with You', '00:04:33', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Don''t Try So Hard', '00:03:39', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Ride the Wild Wind', '00:04:42', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('All God''s People', '00:04:21', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('These Are the Days of Our Lives', '00:04:15', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Delilah', '00:03:32', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('The Hitman', '00:04:56', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Bijou', '00:03:36', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('The Show Must Go On', '00:4:31', (SELECT artist_id FROM Artist WHERE name = 'Queen')),

-- Bohemian Rhapsody (2018 soundtrack) - основные треки
('Somebody to Love (Live at Wembley)', '00:07:53', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Fat Bottomed Girls (Live in Paris)', '00:4:38', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Keep Yourself Alive (Live at the Rainbow)', '00:3:56', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('We Will Rock You (Movie Mix)', '00:2:09', (SELECT artist_id FROM Artist WHERE name = 'Queen')),
('Another One Bites the Dust (Movie Mix)', '00:3:02', (SELECT artist_id FROM Artist WHERE name = 'Queen'));

INSERT INTO Song (title, duration, artist_id) VALUES
-- The Wall (1979)
('In the Flesh?', '00:03:16', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('The Thin Ice', '00:02:27', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Another Brick in the Wall, Part 1', '00:03:11', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('The Happiest Days of Our Lives', '00:01:46', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Another Brick in the Wall, Part 2', '00:03:59', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Mother', '00:05:32', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Goodbye Blue Sky', '00:02:45', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Empty Spaces', '00:02:10', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Young Lust', '00:03:25', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('One of My Turns', '00:03:35', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Don''t Leave Me Now', '00:04:16', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Another Brick in the Wall, Part 3', '00:01:14', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Goodbye Cruel World', '00:01:13', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Hey You', '00:04:40', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Is There Anybody Out There?', '00:02:44', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Nobody Home', '00:03:26', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Vera', '00:01:35', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Bring the Boys Back Home', '00:01:21', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Comfortably Numb', '00:06:23', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('The Show Must Go On', '00:01:36', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('In the Flesh', '00:04:13', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Run Like Hell', '00:04:19', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Waiting for the Worms', '00:03:59', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Stop', '00:00:30', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('The Trial', '00:05:13', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Outside the Wall', '00:01:41', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),

-- Animals (1977)
('Pigs on the Wing, Part 1', '00:01:25', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Dogs', '00:17:05', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Pigs (Three Different Ones)', '00:11:25', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Sheep', '00:10:20', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Pigs on the Wing, Part 2', '00:01:28', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),

-- The Dark Side of the Moon (1973)
('Speak to Me', '00:01:30', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Breathe', '00:02:43', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('On the Run', '00:03:30', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Time', '00:06:53', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('The Great Gig in the Sky', '00:04:36', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Money', '00:06:22', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Us and Them', '00:7:49', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Any Colour You Like', '00:3:26', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Brain Damage', '00:3:50', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Eclipse', '00:2:03', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),

-- The Division Bell (1994)
('Cluster One', '00:05:58', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('What Do You Want from Me', '00:04:21', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Poles Apart', '00:07:04', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Marooned', '00:05:29', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('A Great Day for Freedom', '00:04:17', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Wearing the Inside Out', '00:06:49', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Take It Back', '00:06:12', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Coming Back to Life', '00:06:19', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Keep Talking', '00:06:11', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('Lost for Words', '00:05:14', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd')),
('High Hopes', '00:08:32', (SELECT artist_id FROM Artist WHERE name = 'Pink Floyd'));

INSERT INTO Song (title, duration, artist_id) VALUES
-- Physical Graffiti (1975)
('Custard Pie', '00:04:13', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('The Rover', '00:05:37', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('In My Time of Dying', '00:11:04', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Houses of the Holy', '00:04:02', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Trampled Under Foot', '00:05:37', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Kashmir', '00:08:32', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('In the Light', '00:08:46', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Bron-Yr-Aur', '00:02:06', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Down by the Seaside', '00:05:13', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Ten Years Gone', '00:06:32', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Night Flight', '00:03:36', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('The Wanton Song', '00:04:07', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Boogie with Stu', '00:03:53', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Black Country Woman', '00:04:24', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Sick Again', '00:04:43', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),

-- Led Zeppelin (1969)
('Good Times Bad Times', '00:02:46', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Babe I''m Gonna Leave You', '00:06:41', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('You Shook Me', '00:06:28', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Dazed and Confused', '00:06:26', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Your Time Is Gonna Come', '00:04:34', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Black Mountain Side', '00:02:12', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Communication Breakdown', '00:02:30', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('I Can''t Quit You Baby', '00:04:42', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('How Many More Times', '00:08:28', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),

-- Houses of the Holy (1973)
('The Song Remains the Same', '00:05:32', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('The Rain Song', '00:07:39', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Over the Hills and Far Away', '00:04:50', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('The Crunge', '00:03:17', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Dancing Days', '00:03:43', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('D''yer Mak''er', '00:04:23', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('No Quarter', '00:07:00', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('The Ocean', '00:04:31', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),

-- Led Zeppelin III (1970)
('Immigrant Song', '00:02:26', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Friends', '00:03:55', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Celebration Day', '00:03:29', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Since I''ve Been Loving You', '00:07:25', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Out on the Tiles', '00:04:04', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Gallows Pole', '00:04:56', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Tangerine', '00:03:12', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('That''s the Way', '00:05:37', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Bron-Y-Aur Stomp', '00:04:20', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin')),
('Hats Off to (Roy) Harper', '00:03:41', (SELECT artist_id FROM Artist WHERE name = 'Led Zeppelin'));

INSERT INTO Song (title, duration, artist_id) VALUES
-- Nevermind (1991)
('Smells Like Teen Spirit', '00:05:01', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('In Bloom', '00:04:14', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Come as You Are', '00:03:39', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Breed', '00:03:03', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Lithium', '00:04:17', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Polly', '00:02:57', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Territorial Pissings', '00:02:22', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Drain You', '00:03:43', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Lounge Act', '00:02:36', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Stay Away', '00:03:32', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('On a Plain', '00:03:16', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Something in the Way', '00:03:52', (SELECT artist_id FROM Artist WHERE name = 'Nirvana')),
('Endless, Nameless', '00:06:43', (SELECT artist_id FROM Artist WHERE name = 'Nirvana'));

INSERT INTO Song (title, duration, artist_id) VALUES
('Midnight Train', '00:03:28', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Money Is the Meat in the Coconut', '00:03:14', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Cumberland Gap', '00:03:20', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Airplane', '00:04:56', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Yup', '00:03:21', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Good God a Woman', '00:04:33', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Guitar Man', '00:03:22', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Lindsey Button', '00:03:45', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Come on Over My House', '00:03:31', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Put ''Em Up Solid', '00:03:22', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings')),
('Poor David''s Blues', '00:02:53', (SELECT artist_id FROM Artist WHERE name = 'David Rawlings'));

INSERT INTO Song (title, duration, artist_id) VALUES
('I Don`t Want to Miss a Thing', '00:04:53', (SELECT artist_id FROM Artist WHERE name = 'Aerosmith')),
('Crazy Train', '00:04:11', (SELECT artist_id FROM Artist WHERE name = 'Ozzy Osbourne')),
('Mr. Blue Sky', '00:04:55', (SELECT artist_id FROM Artist WHERE name = 'Elo')),
('Back in Black', '00:04:14', (SELECT artist_id FROM Artist WHERE name = 'AC\CD')),
('Paranoid', '00:02:52', (SELECT artist_id FROM Artist WHERE name = 'Black Sabbath')),
('Dreams', '00:04:14', (SELECT artist_id FROM Artist WHERE name = 'The Cranberries')),
('Remember', '00:04:06', (SELECT artist_id FROM Artist WHERE name = 'Harry Nilsson')),
('Everybody`s Got to Learn Sometime', '00:05:55', (SELECT artist_id FROM Artist WHERE name = 'Beck')),
('Everybody`s Got to Learn Sometime', '00:03:38', (SELECT artist_id FROM Artist WHERE name = 'The Corgies')),
('Skyfall', '00:04:50', (SELECT artist_id FROM Artist WHERE name = 'Adele')),
('Heroes and Villains', '00:04:54', (SELECT artist_id FROM Artist WHERE name = 'The Beach Boys')),
('Moonage Daydream', '00:04:40', (SELECT artist_id FROM Artist WHERE name = 'David Bowie')),
('The Power of Love', '00:06:19', (SELECT artist_id FROM Artist WHERE name = 'Huey Lewis and the News')),
('Back in Time', '00:04:19', (SELECT artist_id FROM Artist WHERE name = 'Huey Lewis and the News')),
('O Children', '00:06:50', (SELECT artist_id FROM Artist WHERE name = 'Nick Cave and the Bad Seeds')),
('Hooked on a Feeling', '00:02:48', (SELECT artist_id FROM Artist WHERE name = 'Blue Swede'));
